#!/bin/bash

# Line Tessellation (LiTe) library
# |||Development version
# Authors: Katarzyna Adamczyk and Kiên Kiêu.
# |||Copyright INRA 2006-yyyy.
# Interdeposit Certification: IDDN.FR.001.030007.000.R.P.2015.000.31235
# License: GPL v3.

# Shell script to be used for publishing LiTe web pages

usage() {
    echo -e "\nusage:\n$0\n"
}

if [ "$#" -ne 0 ]; then
    echo -e "\nShell script $0 does not take any  argument"
    usage
    exit 1
fi
  
repo=https://github.com/kien-kieu/lite

# Get last commit and last release id
CHANGESET=$(git rev-parse --verify HEAD)
TAGLIST=`git tag`
if [ -n "$TAGLIST" ]; then 
    LATESTTAG=$(git describe --tags `git rev-list --tags --max-count=1`)
else
    LATESTTAG=''
fi

# Clean html directory or clone it
mkdir -p build/doc/html
cd build/doc/html
if [ git rev-parse --git-dir > /dev/null 2>&1 ]; then
    git rm -rf .
else
    cd ..
    git clone -b gh-pages "$repo" --single-branch html
    cd html
    git rm -rf .
fi

# Generate HTML documentation
cd ../..
mv CMakeCache.txt CMakeCache.bak
cmake -D BUILD_DOCUMENTATION=ON ..
make Docs
mv CMakeCache.bak CMakeCache.txt 

# Substitute x.y with the latest release id in rlite.html
cd doc/html
if [ -n "$LATESTTAG" ]; then
    RN=${LATESTTAG:1:-1} # e.g. v1.1 -> 1.1
    sed -i 's/where x\.y.*//' rlite.html
    sed -i "s/x\.y/$RN/g" rlite.html
fi

# Commit and push
git add .
git commit -a -m "Doxygen doc for LiTe commit $CHANGESET"
cd ../../..

echo -e "\nDone. Don't forget to push the doc to remote repositories."
echo -e "For instance\n"
echo -e "cd build/doc/html;git push origin gh-pages"
